export const CHARACTER_ROLE_TANK = 'CHARACTER_ROLE_TANK';
export const CHARACTER_ROLE_HEALER = 'CHARACTER_ROLE_HEALER';
export const CHARACTER_ROLE_MELEE = 'CHARACTER_ROLE_MELEE';
export const CHARACTER_ROLE_RANGED = 'CHARACTER_ROLE_RANGED';

export const CHARACTER_CLASS_WARRIOR = 1;
export const CHARACTER_CLASS_PALADIN = 2;
export const CHARACTER_CLASS_HUNTER = 3;
export const CHARACTER_CLASS_ROGUE = 4;
export const CHARACTER_CLASS_PRIEST = 5;
export const CHARACTER_CLASS_DEATH_KNIGHT = 6;
export const CHARACTER_CLASS_SHAMAN = 7;
export const CHARACTER_CLASS_MAGE = 8;
export const CHARACTER_CLASS_WARLOCK = 9;
export const CHARACTER_CLASS_MONK = 10;
export const CHARACTER_CLASS_DRUID = 11;
export const CHARACTER_CLASS_DEMON_HUNTER = 12;

export const DATE_FORMAT = 'dddd, D MMMM YYYY';
export const TIME_FORMAT = 'HH:mm';
