export const RAIDS_LOAD_REQUEST = 'RAIDS_LOAD_REQUEST';
export const RAIDS_LOAD_SUCCESS = 'RAIDS_LOAD_SUCCESS';
export const RAIDS_LOAD_FAILURE = 'RAIDS_LOAD_FAILURE';

export const RAID_UPDATE_SIGNUP_REQUEST = 'RAID_UPDATE_SIGNUP_REQUEST';
export const RAID_UPDATE_SIGNUP_SUCCESS = 'RAID_UPDATE_SIGNUP_SUCCESS';
export const RAID_UPDATE_SIGNUP_FAILURE = 'RAID_UPDATE_SIGNUP_FAILURE';
