export const CHARACTERS_LOAD_REQUEST = 'CHARACTERS_LOAD_REQUEST';
export const CHARACTERS_LOAD_SUCCESS = 'CHARACTERS_LOAD_SUCCESS';
export const CHARACTERS_LOAD_FAILURE = 'CHARACTERS_LOAD_FAILURE';

export const AUDIT_REFRESH_REQUEST = 'AUDIT_REFRESH_REQUEST';
export const AUDIT_REFRESH_SUCCESS = 'AUDIT_REFRESH_SUCCESS';
export const AUDIT_REFRESH_FAILURE = 'AUDIT_REFRESH_FAILURE';
